
gtest_dir = '/usr/src/gtest/lib/'

test_files = [
    'gtest.cpp',
    'test_io.cpp',
    'list_test.cpp',
    'cli_test.cpp',
    'linux/mutex.cpp',
    'linux/io.cpp',
]

files = [
    '../src/cli.c',
    '../src/debug.c',
    '../src/list.cpp',
] + test_files

libs = [
    'pthread',
    'gtest',
]

cflags = [
    '-Wall',
    '-Wextra',
    '-Wswitch-default',
    '-Wswitch-enum',
    '-Wconversion',
    '-Wunused-parameter',

    '-Wno-missing-field-initializers',

    '-g',
    '-DGOOGLETEST',
    '-Isrc',
]

cxxflags = [
    '-std=c++11',
]

env = Environment(CCFLAGS=cflags, CXXFLAGS=cxxflags)
tdd = env.Program(target='tdd', source=files, LIBS=libs)

env.Alias('tdd', tdd)

