
gtest_dir = '/usr/src/gtest/lib/'

files = [
    'gtest.cpp',
    'cli.cpp',
    'list.cpp',
    gtest_dir + 'libgtest.a',
    gtest_dir + 'libgtest_main.a',
]

libs = [
    'pthread',
]

env = Environment(CCFLAGS='-std=c++11 -DCPPUTEST', LINKFLAGS='-lpthread')

env.Program(target='tdd', source=files, LIBS=libs)

