
gtest_dir = '/usr/src/gtest/lib/'

files = [
    'gtest.cpp',
    'cli.cpp',
    'list.cpp',
    'debug.cpp',
    gtest_dir + 'libgtest.a',
    gtest_dir + 'libgtest_main.a',
]

libs = [
    'pthread',
]

cflags = [
    '-std=c++11',
    '-Wall',
    '-g',
    #'-DCPPUTEST',
]

lflags = [
    '-lpthread',
]

env = Environment(CCFLAGS=cflags, LINKFLAGS=lflags)

env.Program(target='tdd', source=files, LIBS=libs)

