
gtest_dir = '/usr/src/gtest/lib/'

files = [
    'gtest.cpp',
    'cli.cpp',
    'list.cpp',
    'debug.cpp',
    'io.cpp',
    'linux/mutex.cpp',
    gtest_dir + 'libgtest.a',
    gtest_dir + 'libgtest_main.a',
]

libs = [
    'pthread',
]

cflags = [
    '-std=c++11',
    '-Wall',
    '-Wextra',
    '-Wswitch-default',
    '-Wswitch-enum',
    '-Wconversion',
    '-Wunused-parameter',

    '-Wno-missing-field-initializers',

    '-g',
    '-DGOOGLETEST',
    '-Isrc',
]

lflags = [
    '-lpthread',
]

env = Environment(CCFLAGS=cflags, LINKFLAGS=lflags)

env.Program(target='tdd', source=files, LIBS=libs)

